import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // User-focused documentation
  userSidebar: [{type: 'autogenerated', dirName: 'user'}],

  // Developer-focused documentation
  developerSidebar: [{type: 'autogenerated', dirName: 'developer'}],

  // LLM Agent-focused documentation (Phase 3)
  agentSidebar: [{type: 'autogenerated', dirName: 'agents'}],

  // Architecture Decision Records
  decisionsSidebar: [{type: 'autogenerated', dirName: 'decisions'}],

  // Design system documentation
  designSidebar: [{type: 'autogenerated', dirName: 'design'}],

  // API Reference (auto-generated)
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],

  // Documentation meta and templates
  metaSidebar: [{type: 'autogenerated', dirName: 'meta'}],
};

export default sidebars;
